[build]
  publish = "frontend/dist"
  command = "cd frontend && rm -rf node_modules/.cache && npm ci && npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://greenix-3.onrender.com"
  NODE_VERSION = "18"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { VITE_API_BASE_URL = "https://greenix-3.onrender.com" }

[context.deploy-preview]
  environment = { VITE_API_BASE_URL = "https://greenix-3.onrender.com" }

[context.branch-deploy]
  environment = { VITE_API_BASE_URL = "https://greenix-3.onrender.com" }