services:
  - type: web
    name: greenix-backend
    env: node
    rootDir: backend/server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/products